blank_lines_upper_bound = 2
condense_wildcard_suffixes = true
edition = "2021"
enum_discrim_align_threshold = 60
fn_params_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Crate"
match_arm_blocks = false
newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true