//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "post_tag")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub object_id: i64,
	pub tag: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "crate::entity::post_object::Entity",
		from = "Column::ObjectId",
		to = "crate::entity::post_object::Column::ObjectId",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	PostObject,
}

impl Related<crate::entity::post_object::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PostObject.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
