//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = true)]
	pub id: i64,
	pub hash: String,
	pub mime_type: String,
	pub block_count: i32,
	pub plain_hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::file_blocks::Entity")]
	FileBlocks,
}

impl Related<super::file_blocks::Entity> for Entity {
	fn to() -> RelationDef { Relation::FileBlocks.def() }
}

impl ActiveModelBehavior for ActiveModel {}
