//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "post_object")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = true)]
	pub id: i64,
	pub object_id: i32,
	#[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
	pub in_reply_to_actor_address: Option<Vec<u8>>,
	pub in_reply_to_object_hash: Option<String>,
	pub file_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::object::Entity",
		from = "Column::ObjectId",
		to = "super::object::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Object,
	#[sea_orm(has_many = "super::post_files::Entity")]
	PostFiles,
	#[sea_orm(has_many = "super::post_tag::Entity")]
	PostTag,
}

impl Related<super::object::Entity> for Entity {
	fn to() -> RelationDef { Relation::Object.def() }
}

impl Related<super::post_files::Entity> for Entity {
	fn to() -> RelationDef { Relation::PostFiles.def() }
}

impl Related<super::post_tag::Entity> for Entity {
	fn to() -> RelationDef { Relation::PostTag.def() }
}

impl ActiveModelBehavior for ActiveModel {}
