//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "post_tag")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = true)]
	pub id: i64,
	pub post_id: i32,
	pub tag: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::post_object::Entity",
		from = "Column::PostId",
		to = "super::post_object::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	PostObject,
}

impl Related<super::post_object::Entity> for Entity {
	fn to() -> RelationDef { Relation::PostObject.def() }
}

impl ActiveModelBehavior for ActiveModel {}
