//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::{
	block::Entity as Block, boost_object::Entity as BoostObject,
	bootstrap_id::Entity as BootstrapId, file::Entity as File, file_blocks::Entity as FileBlocks,
	following::Entity as Following, friend::Entity as Friend, identity::Entity as Identity,
	my_identity::Entity as MyIdentity, node_identity::Entity as NodeIdentity,
	object::Entity as Object, post_files::Entity as PostFiles, post_object::Entity as PostObject,
	post_tag::Entity as PostTag, profile_object::Entity as ProfileObject,
	remembered_fingers::Entity as RememberedFingers,
};
