#!/bin/bash
set -e

if [ "$1" == "configure" ]; then
	if ! getent passwd stonenet; then
		adduser --system --ingroup stonenet --no-create-home stonenet
	fi

	chown -R stonenet:stonenet /var/lib/stonenet
fi

