# The filepath of the SQLite database that stores all media content.
database_path = "/var/lib/stonenet/db.sqlite"

# The IPv4 address to bind to.
ipv4_address = "0.0.0.0"

# The IPv6 address to bind to. Only uncomment this if this is actually supported
# on your network.
#ipv6_address = "::"

# Set the following openness settings to either "bidirectional", "punchable" or
# "unidirectional". Changing this, changes the way that your node advertises the
# way it is able to connect to other nodes. If no ipv6_address is set, the
# relevant ipv8_openness settings are ignored. The same goes for the
# ipv4_address.
# If you comment out one of these settings, that means that the transport
# method is disabled.
#
# Here is what each setting means:
# - bidrectional: Use this if this device is able to receive incomming
#     connections. Only use this when you know you are not behind a NAT device,
#     or when you have forwarded a port on your router. It doesn't matter which
#     external port is used.
# - punchable: Use this if this device is behind a NAT device, but still supports
#     'hole-punching'. Most home routers support UDP hole-punching. Many also
#     support TCP hole-punching, but only enable this is your are certain it
#     works.
# - unidirectional: This means the device is only capable of initiating outgoing
#     connections.
ipv4_udp_openness = "bidirectional"
ipv4_tcp_openness = "unidirectional"
ipv6_udp_openness = "bidirectional"
ipv6_tcp_openness = "unidirectional"

# The ports to bind to. If you comment any of them out, they will use a random
# port available on your system.
# UDP port 53 (DNS) and TCP port 443 (HTTPS) are commonly used on servers, so if
# they are already taken, pick anything else. However, these ports are
# recommended, as they are the arguably the least blocked ports by firewalls.
# If this is for some reason not useable, another recommended port is 37337.
ipv4_udp_port = 37337
ipv6_udp_port = 37337
ipv4_tcp_port = 37337
ipv6_tcp_port = 37337

# If set to true, will run a web server for the user interface
load_web_interface = true

# These are the nodes to fallback to when none of the saved nodes respond
# anymore.
bootstrap_nodes = [
	"205.185.122.225:37337"
]

# Maximum idle time for UDP hole-punching in seconds:
udp_max_idle_time = 60

# The number of nodes to remember in each 'bucket'. This is a technical feature
# that generally does not need to be changed. However, increasing this number
# makes it less likely to be disconnected from the network. Decreasing this
# number saves memory.
# Needs to be 1 or higher.
bucket_size = 4