//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

use crate::{common::*, identity::ActorSignatureV1};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "object")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = true)]
	pub id: i64,
	pub hash: IdType,
	pub actor_id: i64,
	pub sequence: i64,
	pub previous_hash: IdType,
	pub created: i64,
	pub found: i64,
	pub r#type: u8,
	pub signature: ActorSignatureV1,
	pub verified_from_start: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::boost_object::Entity")]
	BoostObject,
	#[sea_orm(
		belongs_to = "super::identity::Entity",
		from = "Column::ActorId",
		to = "super::identity::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Identity,
	#[sea_orm(has_many = "super::post_object::Entity")]
	PostObject,
	#[sea_orm(has_many = "super::profile_object::Entity")]
	ProfileObject,
}

impl Related<super::boost_object::Entity> for Entity {
	fn to() -> RelationDef { Relation::BoostObject.def() }
}

impl Related<super::identity::Entity> for Entity {
	fn to() -> RelationDef { Relation::Identity.def() }
}

impl Related<super::post_object::Entity> for Entity {
	fn to() -> RelationDef { Relation::PostObject.def() }
}

impl ActiveModelBehavior for ActiveModel {}
